// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskAnswer } from "./AskAnswer";

/**
 * Control 频道命令。
 */
export type ControlCommand = { "type": "session_create", close_current: boolean, 
/**
 * 可选工作目录：daemon 拦截层透传给 `session.new` 的 cwd 参数，
 * 落 SessionMeta.cwd 并触发 workspace 自动归属（None = 未分组）。
 */
cwd?: string | null, 
/**
 * 可选工具模式预置（TUI/CLI 壳创建即锁定）：daemon 透传给
 * `session.new`，先落盘再 spawn，worker 首轮即应用。
 */
tool_mode?: string | null, 
/**
 * tool_mode == "custom" 时的自定义工具白名单。
 */
custom_tools?: Array<string>, } | { "type": "session_resume", seed: string, } | { "type": "session_attach", seed: string, } | { "type": "session_close", seed: string, } | { "type": "session_archive", seed: string, } | { "type": "session_unarchive", seed: string, } | { "type": "session_delete", seed: string, } | { "type": "session_shutdown" } | { "type": "agent_reload_config" } | { "type": "set_tool_mode", tool_mode: string, custom_tools?: Array<string>, } | { "type": "interaction_ask_respond", interaction_id: string, answers: Array<AskAnswer>, } | { "type": "interaction_ask_dismiss", interaction_id: string, } | { "type": "plan_review_respond", interaction_id: string, approved: boolean, message?: string | null, autonomous: boolean, } | { "type": "skills_activate", name: string, } | { "type": "skills_reload" } | { "type": "skills_operation", operation_id: string, action: string, name: string, };
