// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";
import type { ConversationMode } from "./ConversationMode";
import type { ImageBlock } from "./ImageBlock";

/**
 * Conversation 频道命令。
 */
export type ConversationCommand = { "type": "conversation_send_message", text: string, images?: Array<ImageBlock>, 
/**
 * Electron main 上传后的会话附件引用；命令中不允许出现本地路径。
 */
attachments?: Array<ContentRef> | null, 
/**
 * 系统级注入（如子代理结果回传）：以 system 角色进入 transcript 并
 * 触发新回合，跳过用户输入专属处理（compliance guard / 技能激活 /
 * todo 模式切换）。false 时行为与普通用户消息完全一致。
 */
as_system: boolean, } | { "type": "conversation_cancel", turn_id?: string | null, } | { "type": "conversation_undo_turn", turn_id: string, } | { "type": "conversation_compact", turn_id?: string | null, } | { "type": "conversation_load_more", before_turn_id: string, count: number, } | { "type": "conversation_set_mode", mode: ConversationMode, };
