// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delivery } from "./Delivery";
import type { RingingEvent } from "./RingingEvent";

/**
 * 事件信封（PLAN 固定字段）。
 *
 * M4 瘦身：`schema`/`version`/`channel`/`server_epoch` 已从信封移除——
 * 版本由端点 URL 承担，epoch/channel 由 SSE 帧 id 承担，batch 级字段承担
 * 聚合上下文；`seed` 保留（单频道连接承载多 seed，必须逐事件路由）。
 */
export type RingingEventEnvelope = { 
/**
 * 可靠性等级：由领域事件定义显式声明，wire 不决定。
 */
delivery: Delivery, 
/**
 * 会话标识。
 */
seed: string, 
/**
 * 每 (server_epoch, channel) 全局递增，供单条 SSE 连接恢复。
 */
stream_seq: number, 
/**
 * 每 (seed, channel) 递增，供领域状态乱序检测。
 */
channel_seq: number, 
/**
 * 每 session/channel 因果序（保留 legacy session_seq 语义）。
 */
session_seq: number, 
/**
 * 事件唯一 id；同 id 至少一次投递但只允许应用一次（幂等）。
 */
event_id: string, 
/**
 * 因果来源（如 command_id），用于关联命令与业务终态。
 */
causation_id?: string | null, 
/**
 * 关联链 id。
 */
correlation_id?: string | null, 
/**
 * 领域状态修订号；terminal 到达后旧 revision 的 replaceable 立即作废。
 */
state_revision?: number, 
/**
 * 服务器发布时间（unix 毫秒）。诊断/遥测用：配合客户端本地到达时间
 * 可测端到端延迟（provider → daemon → SSE → drain → 渲染），定位
 * 流式"攒感"在链路的哪一段。可选——旧事件/回放不保证存在。
 */
server_ts?: number, event: RingingEvent, };
