// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannelSnapshot } from "./RingingChannelSnapshot";

/**
 * 原子恢复一个 session 所需的完整三频道快照。
 */
export type RingingSessionBootstrap = { schema: string, version: number, server_epoch: string, seed: string, control: RingingChannelSnapshot, conversation: RingingChannelSnapshot, tool: RingingChannelSnapshot, };
