// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannel } from "./RingingChannel";

/**
 * `event: ringing.reset_required` 的 data payload。
 */
export type RingingResetRequired = { channel: RingingChannel, 
/**
 * 需要重新拉取 snapshot 的会话。
 */
seed: string, 
/**
 * 服务端该 seed+channel 仍可回放的最早 stream_seq。
 */
earliest_available_seq: number, };
