// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingChannel } from "./RingingChannel";
import type { RingingEventEnvelope } from "./RingingEventEnvelope";

/**
 * 事件批次（main→renderer 必须整 batch 传递，禁止展开为逐事件）。
 */
export type RingingEventBatch = { schema: string, version: number, channel: RingingChannel, seed: string, server_epoch: string, from_stream_seq: number, to_stream_seq: number, envelopes: Array<RingingEventEnvelope>, };
