// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineFailure } from "./TimelineFailure";
import type { TimelineRound } from "./TimelineRound";
import type { TimelineTurnState } from "./TimelineTurnState";

export type TimelineTurn = { turn_id: string, 
/**
 * seq of the TurnOpened entry that created this turn — the authoritative
 * time order across snapshots. `0` means unknown (legacy persisted data);
 * consumers fall back to the turn_id numeric suffix in that case.
 */
created_seq: number, user_text: string, sealed: boolean, state: TimelineTurnState, failure?: TimelineFailure | null, rounds: Array<TimelineRound>, };
