// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineBlock } from "./TimelineBlock";
import type { TimelineFailure } from "./TimelineFailure";
import type { TimelineTool } from "./TimelineTool";
import type { TimelineTurnState } from "./TimelineTurnState";

/**
 * One mutation of the ordered transcript.
 */
export type TimelineEvent = { "type": "turn_opened", user_text: string, } | { "type": "block_opened", block: TimelineBlock, } | { "type": "text_delta", block_id: string, fragment_seq: number, delta: string, } | { "type": "block_checkpoint", block_id: string, text: string, } | { "type": "tool_updated", block_id: string, tool: TimelineTool, } | { "type": "tool_progress", block_id: string, chunk: string, } | { "type": "block_sealed", block_id: string, } | { "type": "round_sealed", is_final: boolean, } | { "type": "turn_sealed", state: TimelineTurnState, failure?: TimelineFailure | null, };
