// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineFailure } from "./TimelineFailure";
import type { TimelineToolPermission } from "./TimelineToolPermission";
import type { TimelineToolState } from "./TimelineToolState";

/**
 * Immutable identity and mutable presentation state for one tool block.
 */
export type TimelineTool = { tool_call_id: string, name: string, state: TimelineToolState, summary?: string | null, 
/**
 * Original structured arguments as supplied by the tool producer.
 */
args_json?: string | null, 
/**
 * The retained tool-output tail. Large output remains an explicit content
 * reference in the eventual transport record rather than being silently
 * truncated by the transcript protocol.
 */
output?: string | null, 
/**
 * Display-plane unified diff (file-mutation tools). Never projected to the
 * model; consumed by the transcript renderer (diff drawer / tool cards).
 */
diff?: string | null, progress?: string, failure?: TimelineFailure | null, permission?: TimelineToolPermission | null, };
