// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * todo_activate 评审项。
 */
export type TodoItem = { id: string, title: string, description: string, 
/**
 * "small" | "medium" | "large"
 */
complexity: string, };
