// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ContentRef } from "./ContentRef";
import type { ToolError } from "./ToolError";
import type { ToolImage } from "./ToolImage";
import type { ToolModelPayload } from "./ToolModelPayload";
import type { ToolStatus } from "./ToolStatus";

export type ToolResult = { status: ToolStatus, summary: string, data: JsonValue, model: ToolModelPayload, 
/**
 * Images to attach to the tool result message (e.g. `read_image`).
 */
images?: Array<ToolImage>, 
/**
 * 展示平面的 unified diff（文件修改类工具的原始 diff 文本）。
 *
 * ⚠ 绝不进入模型投影（`project_for_model` 不携带它）：模型看到的仍是
 * 紧凑摘要行，diff 只供 timeline/前端抽屉消费。发送方在成功路径上
 * 显式填充；缺失时默认 None（向后兼容）。
 */
diff?: string | null, output_ref?: ContentRef | null, error?: ToolError | null, };
